
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Reading notes</title>
  <meta name="description" content="                                                                      1984                                                                                   ...">

  <link rel="stylesheet" href="css/main.css">
  <link rel="canonical" href="http://notes.huytoan.com/">
  <link rel="alternate" type="application/rss+xml" title="Reading notes" href="http://notes.huytoan.com/feed.xml">

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-7405882-12"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-7405882-12');
  </script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="js/readingtime.js"></script>
<script src="js/script.js"></script>

</head>

  <body>
    <header class="site-header">
  <div class="wrapper">
    <a class="site-title" href="/">Reading notes</a> 
    <a class="darkmode-switch"></a>
  </div>
</header>


    <div class="page-content">
      <div class="wrapper">
        <div class="home">
  <ul class="post-list">
    
      
        <li>
          <h2>
            <a class="post-link" href="/1984.html">
              <img class="post-cover" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1532714506l/40961427._SX318_.jpg" />
              1984
            </a>
          </h2>
        </li>
     
      
    
  </ul> 
</div>

      </div>
    </div>
    <footer>

</footer>
    
  </body>
</html>
